on:
  push:
    branches:
      - master

name: bind

permissions:
  contents: write
  issues: read

jobs:
  test-latex-template:
    runs-on: ubuntu-20.04
    name: Release LaTeX Template
    steps:
      - uses: actions/checkout@v4
      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull mbredel/thesis-template:latest
          docker run --volume $(pwd):/thesis-template/ mbredel/thesis-template:latest
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/thesis.pdf