on:
  push:
    branches:
      - master

name: template

permissions:
  contents: write
  issues: read

jobs:
  test-latex-template:
    runs-on: ubuntu-20.04
    name: Test LaTeX Template 
    steps: 
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker pull mbredel/thesis-template:latest
          docker run --volume $(pwd):/thesis-template/ mbredel/thesis-template:latest
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic